# Backtesting configuration for UFC Predictor
# Controls walk-forward simulation and betting parameters

# Walk-forward folding configuration
folding:
  train_years: 3  # Years of training data
  test_months: 3  # Months of test data
  gap_days: 14  # Gap between train and test to prevent leakage

# Time series cross-validation
time_series_cv:
  n_splits: 5
  test_size: 0.2
  gap: 7  # Days gap between train and test

# Odds configuration
odds:
  use: open  # Options: open, close, mid
  slippage_bp: 25  # Basis points of slippage (25bp = 0.25%)
  consensus: false  # Use consensus odds from multiple books
  
  # Book priorities (in order of preference)
  book_priority:
    - TAB
    - FightOdds
    - Pinnacle
    - Bet365
  
  # Vig removal
  remove_vig: true
  vig_method: balanced  # Options: balanced, proportional
  
  # Market efficiency assumptions
  market_efficiency: 0.95  # Assume market is 95% efficient

# Staking configuration
staking:
  method: fractional_kelly  # Options: fractional_kelly, fixed, proportional
  kelly_fraction: 0.25  # Use 25% of full Kelly
  p_lower_quantile: 0.20  # Use 20th percentile for pessimistic Kelly
  
  # Bet size limits
  max_single_pct: 0.05  # Max 5% of bankroll on single bet
  max_multi_pct: 0.02  # Max 2% of bankroll on multi-bet
  min_bet_pct: 0.005  # Min 0.5% of bankroll
  
  # Edge requirements
  min_edge_single: 0.05  # Minimum 5% edge for single bets
  min_edge_multi: 0.08  # Minimum 8% edge for multi-bets
  
  # Parlay configuration
  allow_parlays: true
  max_parlay_legs: 4
  parlay_correlation_penalty: 0.08  # 8% penalty for same-event correlation

# Portfolio optimization
portfolio:
  enabled: true
  method: mean_variance  # Options: mean_variance, max_sharpe, min_variance
  max_bets_per_card: 5
  diversification_penalty: 0.02
  correlation_threshold: 0.5

# Bookmaker limits and constraints
limits:
  max_stake_per_bet: 500
  min_stake: 5
  max_exposure_per_event: 1000
  max_daily_turnover: 5000
  
  # Account restrictions
  account_restrictions:
    enabled: false
    max_win_streak: 10  # Simulate account restriction after N wins
    restriction_probability: 0.1

# Simulation parameters
simulation:
  initial_bankroll: 1000
  commission_rate: 0.0  # Set to 0.02 for 2% commission on wins
  
  # Random seed for reproducibility
  random_seed: 42
  
  # Monte Carlo simulation
  monte_carlo:
    enabled: false
    n_simulations: 1000
    confidence_level: 0.95

# Risk management
risk_management:
  max_drawdown_pct: 0.25  # Stop if drawdown exceeds 25%
  daily_loss_limit_pct: 0.10  # Stop betting if daily loss exceeds 10%
  trailing_stop_loss: false
  stop_loss_pct: 0.50  # Stop if bankroll drops to 50% of peak
  
  # Value at Risk (VaR)
  calculate_var: true
  var_confidence: 0.95
  var_horizon_days: 30

# Performance metrics to track
metrics:
  - roi
  - sharpe_ratio
  - sortino_ratio
  - calmar_ratio
  - max_drawdown
  - win_rate
  - avg_odds
  - clv_win_rate
  - clv_percent
  - profit_factor
  - kelly_criterion_accuracy

# Reporting configuration
reporting:
  generate_plots: true
  save_results: true
  output_dir: artifacts/backtest
  
  # Plot types
  plots:
    - equity_curve
    - drawdown
    - rolling_sharpe
    - bet_distribution
    - clv_distribution
    - calibration_plot
  
  # Report formats
  formats:
    - json
    - csv
    - html
    - pdf

# Market conditions
market_conditions:
  track_market_phases: true
  phases:
    - bull  # Favorites winning more
    - bear  # Underdogs winning more
    - neutral
  
  adjust_for_conditions: false
  condition_window_days: 90

# Advanced features
advanced:
  # Dynamic staking based on confidence
  dynamic_staking: true
  confidence_buckets: [0.55, 0.60, 0.65, 0.70, 0.75]
  stake_multipliers: [0.5, 0.75, 1.0, 1.25, 1.5]
  
  # Bet timing optimization
  optimize_bet_timing: false
  bet_timing_window_hours: 24
  
  # Model ensemble weighting
  use_ensemble_confidence: true
  confidence_method: bootstrap  # Options: bootstrap, cross_validation
  
  # Adaptive Kelly fraction
  adaptive_kelly: false
  kelly_adjustment_period_days: 30
  min_kelly_fraction: 0.1
  max_kelly_fraction: 0.4

# Logging configuration
logging:
  level: INFO
  log_every_bet: false
  log_daily_summary: true
  save_bet_history: true
  
# Debug mode
debug:
  enabled: false
  verbose_output: false
  save_intermediate_results: false
  profile_performance: false